CREATE TABLE "members" (
	"id" SERIAL PRIMARY KEY,
	"password" VARCHAR(50) NOT NULL DEFAULT E'0',
	"fname" VARCHAR(50) NOT NULL DEFAULT E'0',
	"lname" VARCHAR(50) NOT NULL DEFAULT E'0',
	"points" INTEGER NOT NULL DEFAULT E'0'
);