# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeerSampler' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeerSampler
  pod 'CouchbaseLite-Swift'
  pod 'IQKeyboardManagerSwift'

  target 'BeerSamplerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeerSamplerUITests' do
    # Pods for testing
  end

end
